package org.omg.oti

/**
 * <!-- begin-user-doc --> 
 * This is an enumerated type that identifies the type of communication action that was used to generate the Message.
 * <!-- end-user-doc --> 
 */
object UMLMessageSort extends Enumeration {
	
	/**
	 * The enumeration type
	 */
	type UMLMessageSort = Value

	/**
 	* <!-- begin-user-doc --> 
 	* The message was generated by a synchronous call to an operation.
 	* <!-- end-user-doc --> 
 	*/
	val synchCall = Value

	/**
 	* <!-- begin-user-doc --> 
 	* The message was generated by an asynchronous call to an operation; i.e., a CallAction with isSynchronous = false.
 	* <!-- end-user-doc --> 
 	*/
	val asynchCall = Value

	/**
 	* <!-- begin-user-doc --> 
 	* The message was generated by an asynchronous send action.
 	* <!-- end-user-doc --> 
 	*/
	val asynchSignal = Value

	/**
 	* <!-- begin-user-doc --> 
 	* The message designating the creation of another lifeline object.
 	* <!-- end-user-doc --> 
 	*/
	val createMessage = Value

	/**
 	* <!-- begin-user-doc --> 
 	* The message designating the termination of another lifeline.
 	* <!-- end-user-doc --> 
 	*/
	val deleteMessage = Value

	/**
 	* <!-- begin-user-doc --> 
 	* The message is a reply message to an operation call.
 	* <!-- end-user-doc --> 
 	*/
	val reply = Value
}
